name: tunctalk
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dots_indicator: ^2.1.0
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: ^3.0.3
  flutter_facebook_auth: ^6.0.1
  flutter_local_notifications: ^15.1.1
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get: ^4.6.1
  google_sign_in: ^6.1.5
  http: ^1.0.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  loading_animations: ^2.2.0
  package_info: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/videos/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
